# Generated by Django 3.2.25 on 2024-08-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_agendamento_especialidade_parceiro_pessoa_pessoafisica_pessoajuridica_procedimento_representante_tus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.endereco'),
        ),
    ]
