# Generated by Django 3.2.25 on 2024-08-24 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20240824_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='id_pessoa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.pessoa'),
        ),
    ]
