# Generated by Django 3.2.25 on 2024-08-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_pessoafisica_id_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='id_pessoa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.pessoa'),
        ),
    ]
