# Generated by Django 3.2.25 on 2024-08-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_pessoajuridica_id_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceiro',
            old_name='pessoa',
            new_name='id_pessoa',
        ),
    ]
